name: Moderation
main: it.samuconfaa.moderation.Moderation
version: 1.0.0
api-version: 1.21
description: "Plugin per moderazione chat: blacklist parole e controllo CAPS."
author: samuconfaa

commands:
  moderation:
    description: "Comando principale per gestire la moderazione chat"
    usage: "/moderation <add|remove|check|reload> [word]"

permissions:
  moderation.admin:
    description: "Permette di usare tutti i sottocomandi"
    default: op
    children:
      moderation.check: true
      moderation.staff: true
      moderation.reload: true
      moderation.add: true
      moderation.remove: true
      moderation.history: true

  moderation.staff:
    description: "Per ricevere le segnalazioni"
    default: op

  moderation.add:
    description: "Permette di usare il sottocomando add"
    default: op

  moderation.reload:
    description: "Permette di usare il sottocomando reload"
    default: op

  moderation.remove:
    description: "Permette di usare il sottocomando remove"
    default: op

  moderation.history:
    description: "Permette di usare il sottocomando history"
    default: op

  moderation.check:
    description: "Permette di usare il sottocomando check"
    default: true
