name: Moderation
main: it.samuconfaa.moderation.Moderation
version: 1.1.1
api-version: 1.21
description: "Plugin per moderazione chat: blacklist parole e controllo CAPS."
author: samuconfaa

commands:
  moderation:
    description: "Comando principale per gestire la moderazione chat"
    usage: "/moderation <add|remove|check|reload|export|import|history> [args]"

permissions:
  moderation.admin:
    description: "Permette di usare tutti i sottocomandi"
    default: op
    children:
      moderation.check: true
      moderation.staff: true
      moderation.reload: true
      moderation.add: true
      moderation.remove: true
      moderation.history: true
      moderation.bypass: true
      moderation.export: true
      moderation.import: true

  moderation.staff:
    description: "Per ricevere le segnalazioni"
    default: op

  moderation.add:
    description: "Permette di usare il sottocomando add"
    default: op

  moderation.reload:
    description: "Permette di usare il sottocomando reload"
    default: op

  moderation.remove:
    description: "Permette di usare il sottocomando remove"
    default: op

  moderation.history:
    description: "Permette di usare il sottocomando history"
    default: op

  moderation.check:
    description: "Permette di usare il sottocomando check"
    default: true

  moderation.bypass:
    description: "Permette di inviare tutti i messaggi senza censure"
    default: op

  moderation.export:
    description: "Permette di esportare blacklist e whitelist"
    default: op

  moderation.import:
    description: "Permette di importare blacklist e whitelist"
    default: op